config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    devise_scope :user do
      root to: 'devise/sessions#new'
    end

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'users/registrations',
    }

    resources :users, only: :index do
      resources :books, only: :index, controller: 'users/books'
      resources :reports, only: :index, controller: 'users/reports'
      resources :followings, only: :index, controller: 'users/followings'
      resources :followers, only: :index, controller: 'users/followers'
    end

    resources :profiles, only: %i[show edit update]

    resources :follows, only: %i[create destroy]

    resources :books do
      resources :comments, only: %i[create edit update destroy], module: :books
    end

    resources :reports do
      resources :comments, only: %i[create edit update destroy], module: :reports
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar
  before_create :attach_default_avatar

  validates :user_id, uniqueness: true
  validates :zipcode, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, allow_blank: true }, on: :update

  def resized_avatar(size)
    resize =
      case size
      when :sm
        [50, 50]
      when :md
        [70, 70]
      when :lg
        [200, 200]
      else
        size
      end
    self.avatar.variant(resize_to_fill: resize)
  end

  private
    def attach_default_avatar
      path = Rails.root.join('app', 'frontend', 'images', 'default_avatar.png')
      default_avatar = File.open(path)
      self.avatar.attach(io: default_avatar, filename: 'dafault_avatar.png', content_type: 'image/png')
    end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show edit update]
  before_action :authenticate_profile, only: %i[edit update]

  def show
    @user = @profile.user
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: t('flash.update')
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = User.find(params[:id]).profile
    end

    def authenticate_profile
      redirect_to @profile, alert: t('dictionary.alert.authenticate') unless @profile.user == current_user
    end

    def profile_params
      params.require(:profile).permit(:name, :zipcode, :address, :self_introduction, :avatar)
    end
end

app/views/profiles/_follow.html.erb
<%= form_with(model: current_user.active_follows.build(followed_id: user.id)) do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit t('profiles.show.follow'), class: 'btn btn-primary', id: 'follow_btn' %>
<% end %>

app/views/profiles/_unfollow.html.erb
<%= form_with(model: current_user.active_follows.find_by(followed_id: user.id), method: :delete) do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit t('profiles.show.unfollow'), class: 'btn btn-danger', id: 'unfollow_btn' %>
<% end %>

app/views/profiles/edit.html.erb
<h1><%= t '.title' %></h1>

<%= form_with(model: @profile, local: true) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <p><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</p>

      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :name, class: 'col-md-2 col-form-label' %>
    <div class="col-md-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :zipcode, class: 'col-md-2 col-form-label' %>
    <div class="col-md-10">
      <%= f.text_field :zipcode, class: 'form-control', rows: 5 %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :address, class: 'col-md-2 col-form-label' %>
    <div class="col-md-10">
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :self_introduction, class: 'col-md-2 col-form-label' %>
    <div class="col-md-10">
      <%= f.text_area :self_introduction, class: 'form-control', rows: 7 %>
    </div>
  </div>

  <div class="actions text-center">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/index.html.erb
<h1><%= t '.title' %></h1>

<ul>
  <% @profiles.each do |profile| %>
    <li class="h4 py-1"><a href="profiles/<%= profile.user.id %>"><%= profile.user.username %></a></li>
  <% end %>
</ul>

app/views/profiles/show.html.erb
<h1><%= t '.title' %></h1>

<h2 class="d-flex justify-content-between align-items-center mb-0">
  <p class="mb-0">
    <%= image_tag @profile.resized_avatar(:md), style: 'border-radius: 50%;' %>
    <span class="ml-2"><%= @user.username %></span>
  </p>
  <div>
    <%= link_to t('.show_reports'), user_reports_path(@user), class: 'mr-3' %>
    <%= link_to t('.show_books'), user_books_path(@user) %>
  </div>
</h2>
<div class="follow d-flex justify-content-start align-items-center mt-3">
  <div class="links">
    <span id="followings"><%= link_to count_followings(@user), user_followings_path(@user), class: 'mr-2' %></span>
    <span id="followers"><%= link_to count_followers(@user), user_followers_path(@user) %></span>
  </div>

  <% unless current_user == @user %>
    <div id="follow_form" class="ml-3">
      <% if current_user.following?(@user) %>
        <%= render 'unfollow', user: @user %>
      <% else %>
        <%= render 'follow', user: @user %>
      <% end %>
    </div>
  <% end %>
</div>

<table class="table table-bordered mb-4">
  <tbody>
    <tr>
      <th><%= Profile.human_attribute_name(:name) %></th>
      <td><%= @profile.name %></td>
    </tr>

    <tr>
      <th><%= Profile.human_attribute_name(:zipcode) %></th>
      <td><%= @profile.zipcode %></td>
    </tr>

    <tr>
      <th><%= Profile.human_attribute_name(:address) %></th>
      <td><%= @profile.address %></td>
    </tr>

    <tr>
      <th><%= Profile.human_attribute_name(:self_introduction) %></th>
      <br>
      <td><%= simple_format h @profile.self_introduction %></td>
    </tr>
  </tbody>
</table>

<% if current_user == @profile.user %>
  <%= link_to t('dictionary.button.edit'), edit_profile_path(current_user) %> |
<% end %>
<%= link_to t('dictionary.button.back'), users_path %>