config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    devise_scope :user do
      root to: 'devise/sessions#new'
    end

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'users/registrations',
    }

    resources :users, only: :index do
      resources :books, only: :index, controller: 'users/books'
      resources :reports, only: :index, controller: 'users/reports'
      resources :followings, only: :index, controller: 'users/followings'
      resources :followers, only: :index, controller: 'users/followers'
    end

    resources :profiles, only: %i[show edit update]

    resources :follows, only: %i[create destroy]

    resources :books do
      resources :comments, only: %i[create edit update destroy], module: :books
    end

    resources :reports do
      resources :comments, only: %i[create edit update destroy], module: :reports
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  include Order

  belongs_to :user
  has_many :comments, as: :commentable

  validates :title, presence: true
end

app/controllers/reports/comments_controller.rb
# frozen_string_literal: true

class Reports::CommentsController < CommentsController
  private
    def set_commentable
      @commentable = Report.find(params[:report_id])
    end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: :show
  before_action :set_my_report, only: %i[edit update destroy]

  def index
    @reports =
      Report
        .includes(user: { profile: { avatar_attachment: :blob } })
        .recent
        .page(params[:page])
  end

  def show
  end

  def new
    @report = Report.new
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    @report.user = current_user

    if @report.save
      redirect_to @report, notice: t('flash.new')
    else
      render :new
    end
  end

  def update
    if @report.update(report_params)
      redirect_to @report, notice: t('flash.update')
    else
      render :edit
    end
  end

  def destroy
    @report.destroy

    redirect_to user_reports_path(current_user), notice: t('flash.destroy')
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def set_my_report
      @report = current_user.reports.find_by(id: params[:id])
      redirect_to user_reports_url(current_user), alert: t('dictionary.alert.authenticate') unless @report
    end

    def report_params
      params.require(:report).permit(:title, :date, :content)
    end
end

app/controllers/users/reports_controller.rb
# frozen_string_literal: true

class Users::ReportsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @reports = @user.reports.recent.page(params[:page])
  end
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
  require 'redcarpet'
  require 'coderay'

  class MarkdownRenderer < Redcarpet::Render::HTML
    def block_code(code, language)
      lang =
        case language.to_s
        when 'rb'
          'ruby'
        when 'yml'
          'yaml'
        when 'css'
          'css'
        when 'html'
          'html'
        when ''
          'md'
        else
          language
        end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = MarkdownRenderer.new(filter_html: true, hard_wrap: true)
    options = {
        autolink: true,
        space_after_headers: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        tables: true,
        hard_wrap: true,
        xhtml: true,
        lax_html_blocks: true,
        strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text).html_safe
  end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <p><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</p>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control col-md-7' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, value: Date.today, class: 'form-control col-md-7' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control', rows: 10 %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary mb-3' %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', report: @report %>

<%= link_to t('dictionary.button.show'), @report %> |
<%= link_to t('dictionary.button.back'), user_reports_path(@report.user) %>

app/views/reports/index.html.erb
<h1><%= t '.title' %></h1>

<div class="card mb-3">
  <ul class="list-group list-group-flush reports-list index">
    <% @reports.each do |report| %>
      <li class="list-group-item d-flex justify-content-between">
        <div class="d-flex">
          <%= link_to image_tag(user_avatar(user: report.user), style: 'border-radius: 50%'), report.user.profile %>
          <div class="texts ml-3">
            <p class="mb-0">
              <%= link_to report.title, report, class: 'text-dark link' %>
            </p>
            <p class="mb-0"><%= l report.created_at %></p>
          </div>
        </div>
        <div class="links">
          <% if current_user == report.user %>
            <%= link_to t('dictionary.button.edit'), edit_report_path(report) %>
            <%= link_to t('dictionary.button.destroy'), report, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to t('dictionary.button.new'), new_report_path, class: 'btn btn-primary mb-3' %>

<%= paginate @reports %>
<div class="paginate-info"><%= page_entries_info @reports %></div>

app/views/reports/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', report: @report %>

<%= link_to t('dictionary.button.back'), :back %>

app/views/reports/show.html.erb
<div class="report row mb-3">
  <div class="col-md-1 text-center mb-2 p-0">
    <%= link_to image_tag(user_avatar(user: @report.user, size: :md), style: 'border-radius: 50%;'), @report.user.profile %>
  </div>
  <div class="col-md-11 pl-4">
    <div class="card">
      <div class="card-header py-2">
        <small>
          <%= link_to @report.user.username, @report.user.profile, class: 'mr-1 link-underline' %>
          <span class="text-muted"><%= l @report.date %> <%= t '.title' %></span>
        </small>
      </div>
      <div class="card-body">
        <h1 class="card-title border-bottom pb-1 h2"><%= @report.title %></h1>
        <p class="card-text"><%= markdown(@report.content) %></p>
      </div>
    </div>
  </div>
</div>
<% if current_user == @report.user %>
  <%= link_to t('dictionary.button.edit'), edit_report_path(@report) %> |
<% end %>
<%= link_to t('dictionary.button.back'), user_reports_path(@report.user) %>

<%= render 'comments/comments', commentable: @report, comment: current_user.comments.build %>