config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    devise_scope :user do
      root to: 'devise/sessions#new'
    end

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: 'users/registrations',
    }

    resources :users, only: :index do
      resources :books, only: :index, controller: 'users/books'
      resources :reports, only: :index, controller: 'users/reports'
      resources :followings, only: :index, controller: 'users/followings'
      resources :followers, only: :index, controller: 'users/followers'
    end

    resources :profiles, only: %i[show edit update]

    resources :follows, only: %i[create destroy]

    resources :books do
      resources :comments, only: %i[create edit update destroy], module: :books
    end

    resources :reports do
      resources :comments, only: %i[create edit update destroy], module: :reports
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BooksApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-md-5">
      <%= link_to "Book App", books_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav w-100 d-flex justify-content-end">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to t('reports.index.title'), reports_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to t('users.index.title'), users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to Profile.model_name.human, profile_path(current_user.id), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to t('devise.registrations.edit.title', resource: User.model_name.human), edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to t('devise.sessions.destroy.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to t('devise.registrations.new.sign_up'), new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to t('devise.sessions.new.sign_in'), new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container py-3">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>
</body>

</html>